name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    environment:
      name: production
      url: https://github.com

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Lightsail Host Key to known_hosts
        run: ssh-keyscan -H 54.179.227.134 >> $HOME/.ssh/known_hosts

      - name: Install Dependencies
        run: npm install --prefix frontend

      - name: Build Vue.js Application
        run: npm run build --prefix frontend

      - name: Deploy to Lightsail
        run: scp -r frontend/dist/* ubuntu@54.179.227.134:/projects/coffeecupdigital/frontend
